#!/bin/bash

# chmod +x ./asm
# ./asm input.s

asm_script="$1"
out_script=$(echo "$asm_script" | sed 's/\.s/\.o/')

gcc -c $asm_script && ld $out_script && ./a.out
echo "$asm_script: $?"

rm $out_script
